volumes:
  pg_Wallet:

services:
  wallet_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=wallet_db
    volumes:
      - pg_Wallet:/var/lib/postgresql/data

    ports:
      - "5433:5432"

  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - wallet_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://wallet_db:5432/wallet_db'
      JAVA_OPTS: '-Xmx512m'


